name: CI

on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: "${{ matrix.abi }}-bit / ${{ matrix.engine }} / GAP ${{ matrix.gap-branch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11
        abi:
          - 64
        engine:
          - nauty

        include:
          - gap-branch: master
            abi: 32
            engine: nauty
          - gap-branch: master
            abi: 64
            engine: bliss

    env:
      GRAPE_NAUTY: ${{ matrix.engine == 'nauty' }}

    steps:
      - uses: actions/checkout@v2
      - name: "Install bliss"
        if: ${{ matrix.engine == 'bliss' }}
        run: sudo apt-get install bliss
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.abi }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v2
